name: ponto_diario
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  geolocator: ^6.2.0
  get: ^3.24.0
  slide_digital_clock: ^1.0.0
  shared_preferences: ^0.5.12+4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
